// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newBusinessUnit(db *gorm.DB, opts ...gen.DOOption) businessUnit {
	_businessUnit := businessUnit{}

	_businessUnit.businessUnitDo.UseDB(db, opts...)
	_businessUnit.businessUnitDo.UseModel(&model.BusinessUnit{})

	tableName := _businessUnit.businessUnitDo.TableName()
	_businessUnit.ALL = field.NewAsterisk(tableName)
	_businessUnit.ID = field.NewInt64(tableName, "id")
	_businessUnit.CreatedAt = field.NewTime(tableName, "created_at")
	_businessUnit.UpdatedAt = field.NewTime(tableName, "updated_at")
	_businessUnit.Name = field.NewString(tableName, "name")
	_businessUnit.Description = field.NewString(tableName, "description")
	_businessUnit.ProjectID = field.NewInt64(tableName, "project_id")

	_businessUnit.fillFieldMap()

	return _businessUnit
}

type businessUnit struct {
	businessUnitDo businessUnitDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Name        field.String
	Description field.String
	ProjectID   field.Int64

	fieldMap map[string]field.Expr
}

func (b businessUnit) Table(newTableName string) *businessUnit {
	b.businessUnitDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b businessUnit) As(alias string) *businessUnit {
	b.businessUnitDo.DO = *(b.businessUnitDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *businessUnit) updateTableName(table string) *businessUnit {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.Name = field.NewString(table, "name")
	b.Description = field.NewString(table, "description")
	b.ProjectID = field.NewInt64(table, "project_id")

	b.fillFieldMap()

	return b
}

func (b *businessUnit) WithContext(ctx context.Context) *businessUnitDo {
	return b.businessUnitDo.WithContext(ctx)
}

func (b businessUnit) TableName() string { return b.businessUnitDo.TableName() }

func (b businessUnit) Alias() string { return b.businessUnitDo.Alias() }

func (b businessUnit) Columns(cols ...field.Expr) gen.Columns {
	return b.businessUnitDo.Columns(cols...)
}

func (b *businessUnit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *businessUnit) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 6)
	b.fieldMap["id"] = b.ID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["name"] = b.Name
	b.fieldMap["description"] = b.Description
	b.fieldMap["project_id"] = b.ProjectID
}

func (b businessUnit) clone(db *gorm.DB) businessUnit {
	b.businessUnitDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b businessUnit) replaceDB(db *gorm.DB) businessUnit {
	b.businessUnitDo.ReplaceDB(db)
	return b
}

type businessUnitDo struct{ gen.DO }

func (b businessUnitDo) Debug() *businessUnitDo {
	return b.withDO(b.DO.Debug())
}

func (b businessUnitDo) WithContext(ctx context.Context) *businessUnitDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b businessUnitDo) ReadDB() *businessUnitDo {
	return b.Clauses(dbresolver.Read)
}

func (b businessUnitDo) WriteDB() *businessUnitDo {
	return b.Clauses(dbresolver.Write)
}

func (b businessUnitDo) Session(config *gorm.Session) *businessUnitDo {
	return b.withDO(b.DO.Session(config))
}

func (b businessUnitDo) Clauses(conds ...clause.Expression) *businessUnitDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b businessUnitDo) Returning(value interface{}, columns ...string) *businessUnitDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b businessUnitDo) Not(conds ...gen.Condition) *businessUnitDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b businessUnitDo) Or(conds ...gen.Condition) *businessUnitDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b businessUnitDo) Select(conds ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b businessUnitDo) Where(conds ...gen.Condition) *businessUnitDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b businessUnitDo) Order(conds ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b businessUnitDo) Distinct(cols ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b businessUnitDo) Omit(cols ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b businessUnitDo) Join(table schema.Tabler, on ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b businessUnitDo) LeftJoin(table schema.Tabler, on ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b businessUnitDo) RightJoin(table schema.Tabler, on ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b businessUnitDo) Group(cols ...field.Expr) *businessUnitDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b businessUnitDo) Having(conds ...gen.Condition) *businessUnitDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b businessUnitDo) Limit(limit int) *businessUnitDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b businessUnitDo) Offset(offset int) *businessUnitDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b businessUnitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *businessUnitDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b businessUnitDo) Unscoped() *businessUnitDo {
	return b.withDO(b.DO.Unscoped())
}

func (b businessUnitDo) Create(values ...*model.BusinessUnit) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b businessUnitDo) CreateInBatches(values []*model.BusinessUnit, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b businessUnitDo) Save(values ...*model.BusinessUnit) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b businessUnitDo) First() (*model.BusinessUnit, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessUnit), nil
	}
}

func (b businessUnitDo) Take() (*model.BusinessUnit, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessUnit), nil
	}
}

func (b businessUnitDo) Last() (*model.BusinessUnit, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessUnit), nil
	}
}

func (b businessUnitDo) Find() ([]*model.BusinessUnit, error) {
	result, err := b.DO.Find()
	return result.([]*model.BusinessUnit), err
}

func (b businessUnitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BusinessUnit, err error) {
	buf := make([]*model.BusinessUnit, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b businessUnitDo) FindInBatches(result *[]*model.BusinessUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b businessUnitDo) Attrs(attrs ...field.AssignExpr) *businessUnitDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b businessUnitDo) Assign(attrs ...field.AssignExpr) *businessUnitDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b businessUnitDo) Joins(fields ...field.RelationField) *businessUnitDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b businessUnitDo) Preload(fields ...field.RelationField) *businessUnitDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b businessUnitDo) FirstOrInit() (*model.BusinessUnit, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessUnit), nil
	}
}

func (b businessUnitDo) FirstOrCreate() (*model.BusinessUnit, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BusinessUnit), nil
	}
}

func (b businessUnitDo) FindByPage(offset int, limit int) (result []*model.BusinessUnit, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b businessUnitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b businessUnitDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b businessUnitDo) Delete(models ...*model.BusinessUnit) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *businessUnitDo) withDO(do gen.Dao) *businessUnitDo {
	b.DO = *do.(*gen.DO)
	return b
}
