// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newCDConfig(db *gorm.DB, opts ...gen.DOOption) cDConfig {
	_cDConfig := cDConfig{}

	_cDConfig.cDConfigDo.UseDB(db, opts...)
	_cDConfig.cDConfigDo.UseModel(&model.CDConfig{})

	tableName := _cDConfig.cDConfigDo.TableName()
	_cDConfig.ALL = field.NewAsterisk(tableName)
	_cDConfig.ID = field.NewInt64(tableName, "id")
	_cDConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_cDConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cDConfig.Name = field.NewString(tableName, "name")
	_cDConfig.RenderEngine = field.NewString(tableName, "render_engine")
	_cDConfig.ValuesYAML = field.NewString(tableName, "values_yaml")
	_cDConfig.ReleaseStrategy = field.NewField(tableName, "release_strategy")

	_cDConfig.fillFieldMap()

	return _cDConfig
}

type cDConfig struct {
	cDConfigDo cDConfigDo

	ALL             field.Asterisk
	ID              field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Name            field.String
	RenderEngine    field.String
	ValuesYAML      field.String
	ReleaseStrategy field.Field

	fieldMap map[string]field.Expr
}

func (c cDConfig) Table(newTableName string) *cDConfig {
	c.cDConfigDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cDConfig) As(alias string) *cDConfig {
	c.cDConfigDo.DO = *(c.cDConfigDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cDConfig) updateTableName(table string) *cDConfig {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.Name = field.NewString(table, "name")
	c.RenderEngine = field.NewString(table, "render_engine")
	c.ValuesYAML = field.NewString(table, "values_yaml")
	c.ReleaseStrategy = field.NewField(table, "release_strategy")

	c.fillFieldMap()

	return c
}

func (c *cDConfig) WithContext(ctx context.Context) *cDConfigDo { return c.cDConfigDo.WithContext(ctx) }

func (c cDConfig) TableName() string { return c.cDConfigDo.TableName() }

func (c cDConfig) Alias() string { return c.cDConfigDo.Alias() }

func (c cDConfig) Columns(cols ...field.Expr) gen.Columns { return c.cDConfigDo.Columns(cols...) }

func (c *cDConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cDConfig) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["render_engine"] = c.RenderEngine
	c.fieldMap["values_yaml"] = c.ValuesYAML
	c.fieldMap["release_strategy"] = c.ReleaseStrategy
}

func (c cDConfig) clone(db *gorm.DB) cDConfig {
	c.cDConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cDConfig) replaceDB(db *gorm.DB) cDConfig {
	c.cDConfigDo.ReplaceDB(db)
	return c
}

type cDConfigDo struct{ gen.DO }

func (c cDConfigDo) Debug() *cDConfigDo {
	return c.withDO(c.DO.Debug())
}

func (c cDConfigDo) WithContext(ctx context.Context) *cDConfigDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cDConfigDo) ReadDB() *cDConfigDo {
	return c.Clauses(dbresolver.Read)
}

func (c cDConfigDo) WriteDB() *cDConfigDo {
	return c.Clauses(dbresolver.Write)
}

func (c cDConfigDo) Session(config *gorm.Session) *cDConfigDo {
	return c.withDO(c.DO.Session(config))
}

func (c cDConfigDo) Clauses(conds ...clause.Expression) *cDConfigDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cDConfigDo) Returning(value interface{}, columns ...string) *cDConfigDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cDConfigDo) Not(conds ...gen.Condition) *cDConfigDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cDConfigDo) Or(conds ...gen.Condition) *cDConfigDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cDConfigDo) Select(conds ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cDConfigDo) Where(conds ...gen.Condition) *cDConfigDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cDConfigDo) Order(conds ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cDConfigDo) Distinct(cols ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cDConfigDo) Omit(cols ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cDConfigDo) Join(table schema.Tabler, on ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cDConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cDConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cDConfigDo) Group(cols ...field.Expr) *cDConfigDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cDConfigDo) Having(conds ...gen.Condition) *cDConfigDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cDConfigDo) Limit(limit int) *cDConfigDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cDConfigDo) Offset(offset int) *cDConfigDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cDConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cDConfigDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cDConfigDo) Unscoped() *cDConfigDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cDConfigDo) Create(values ...*model.CDConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cDConfigDo) CreateInBatches(values []*model.CDConfig, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cDConfigDo) Save(values ...*model.CDConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cDConfigDo) First() (*model.CDConfig, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CDConfig), nil
	}
}

func (c cDConfigDo) Take() (*model.CDConfig, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CDConfig), nil
	}
}

func (c cDConfigDo) Last() (*model.CDConfig, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CDConfig), nil
	}
}

func (c cDConfigDo) Find() ([]*model.CDConfig, error) {
	result, err := c.DO.Find()
	return result.([]*model.CDConfig), err
}

func (c cDConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CDConfig, err error) {
	buf := make([]*model.CDConfig, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cDConfigDo) FindInBatches(result *[]*model.CDConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cDConfigDo) Attrs(attrs ...field.AssignExpr) *cDConfigDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cDConfigDo) Assign(attrs ...field.AssignExpr) *cDConfigDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cDConfigDo) Joins(fields ...field.RelationField) *cDConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cDConfigDo) Preload(fields ...field.RelationField) *cDConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cDConfigDo) FirstOrInit() (*model.CDConfig, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CDConfig), nil
	}
}

func (c cDConfigDo) FirstOrCreate() (*model.CDConfig, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CDConfig), nil
	}
}

func (c cDConfigDo) FindByPage(offset int, limit int) (result []*model.CDConfig, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cDConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cDConfigDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cDConfigDo) Delete(models ...*model.CDConfig) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cDConfigDo) withDO(do gen.Dao) *cDConfigDo {
	c.DO = *do.(*gen.DO)
	return c
}
