// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newDeployPlan(db *gorm.DB, opts ...gen.DOOption) deployPlan {
	_deployPlan := deployPlan{}

	_deployPlan.deployPlanDo.UseDB(db, opts...)
	_deployPlan.deployPlanDo.UseModel(&model.DeployPlan{})

	tableName := _deployPlan.deployPlanDo.TableName()
	_deployPlan.ALL = field.NewAsterisk(tableName)
	_deployPlan.ID = field.NewInt64(tableName, "id")
	_deployPlan.CreatedAt = field.NewTime(tableName, "created_at")
	_deployPlan.UpdatedAt = field.NewTime(tableName, "updated_at")
	_deployPlan.Name = field.NewString(tableName, "name")
	_deployPlan.Description = field.NewString(tableName, "description")
	_deployPlan.BusinessUnitID = field.NewInt64(tableName, "business_unit_id")
	_deployPlan.CIConfigID = field.NewInt64(tableName, "ci_config_id")
	_deployPlan.CDConfigID = field.NewInt64(tableName, "cd_config_id")
	_deployPlan.InstanceConfigID = field.NewInt64(tableName, "instance_config_id")

	_deployPlan.fillFieldMap()

	return _deployPlan
}

type deployPlan struct {
	deployPlanDo deployPlanDo

	ALL              field.Asterisk
	ID               field.Int64
	CreatedAt        field.Time
	UpdatedAt        field.Time
	Name             field.String
	Description      field.String
	BusinessUnitID   field.Int64
	CIConfigID       field.Int64
	CDConfigID       field.Int64
	InstanceConfigID field.Int64

	fieldMap map[string]field.Expr
}

func (d deployPlan) Table(newTableName string) *deployPlan {
	d.deployPlanDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deployPlan) As(alias string) *deployPlan {
	d.deployPlanDo.DO = *(d.deployPlanDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deployPlan) updateTableName(table string) *deployPlan {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.Name = field.NewString(table, "name")
	d.Description = field.NewString(table, "description")
	d.BusinessUnitID = field.NewInt64(table, "business_unit_id")
	d.CIConfigID = field.NewInt64(table, "ci_config_id")
	d.CDConfigID = field.NewInt64(table, "cd_config_id")
	d.InstanceConfigID = field.NewInt64(table, "instance_config_id")

	d.fillFieldMap()

	return d
}

func (d *deployPlan) WithContext(ctx context.Context) *deployPlanDo {
	return d.deployPlanDo.WithContext(ctx)
}

func (d deployPlan) TableName() string { return d.deployPlanDo.TableName() }

func (d deployPlan) Alias() string { return d.deployPlanDo.Alias() }

func (d deployPlan) Columns(cols ...field.Expr) gen.Columns { return d.deployPlanDo.Columns(cols...) }

func (d *deployPlan) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deployPlan) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["name"] = d.Name
	d.fieldMap["description"] = d.Description
	d.fieldMap["business_unit_id"] = d.BusinessUnitID
	d.fieldMap["ci_config_id"] = d.CIConfigID
	d.fieldMap["cd_config_id"] = d.CDConfigID
	d.fieldMap["instance_config_id"] = d.InstanceConfigID
}

func (d deployPlan) clone(db *gorm.DB) deployPlan {
	d.deployPlanDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deployPlan) replaceDB(db *gorm.DB) deployPlan {
	d.deployPlanDo.ReplaceDB(db)
	return d
}

type deployPlanDo struct{ gen.DO }

func (d deployPlanDo) Debug() *deployPlanDo {
	return d.withDO(d.DO.Debug())
}

func (d deployPlanDo) WithContext(ctx context.Context) *deployPlanDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deployPlanDo) ReadDB() *deployPlanDo {
	return d.Clauses(dbresolver.Read)
}

func (d deployPlanDo) WriteDB() *deployPlanDo {
	return d.Clauses(dbresolver.Write)
}

func (d deployPlanDo) Session(config *gorm.Session) *deployPlanDo {
	return d.withDO(d.DO.Session(config))
}

func (d deployPlanDo) Clauses(conds ...clause.Expression) *deployPlanDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deployPlanDo) Returning(value interface{}, columns ...string) *deployPlanDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deployPlanDo) Not(conds ...gen.Condition) *deployPlanDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deployPlanDo) Or(conds ...gen.Condition) *deployPlanDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deployPlanDo) Select(conds ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deployPlanDo) Where(conds ...gen.Condition) *deployPlanDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deployPlanDo) Order(conds ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deployPlanDo) Distinct(cols ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deployPlanDo) Omit(cols ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deployPlanDo) Join(table schema.Tabler, on ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deployPlanDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deployPlanDo) RightJoin(table schema.Tabler, on ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deployPlanDo) Group(cols ...field.Expr) *deployPlanDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deployPlanDo) Having(conds ...gen.Condition) *deployPlanDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deployPlanDo) Limit(limit int) *deployPlanDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deployPlanDo) Offset(offset int) *deployPlanDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deployPlanDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deployPlanDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deployPlanDo) Unscoped() *deployPlanDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deployPlanDo) Create(values ...*model.DeployPlan) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deployPlanDo) CreateInBatches(values []*model.DeployPlan, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deployPlanDo) Save(values ...*model.DeployPlan) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deployPlanDo) First() (*model.DeployPlan, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeployPlan), nil
	}
}

func (d deployPlanDo) Take() (*model.DeployPlan, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeployPlan), nil
	}
}

func (d deployPlanDo) Last() (*model.DeployPlan, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeployPlan), nil
	}
}

func (d deployPlanDo) Find() ([]*model.DeployPlan, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeployPlan), err
}

func (d deployPlanDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeployPlan, err error) {
	buf := make([]*model.DeployPlan, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deployPlanDo) FindInBatches(result *[]*model.DeployPlan, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deployPlanDo) Attrs(attrs ...field.AssignExpr) *deployPlanDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deployPlanDo) Assign(attrs ...field.AssignExpr) *deployPlanDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deployPlanDo) Joins(fields ...field.RelationField) *deployPlanDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deployPlanDo) Preload(fields ...field.RelationField) *deployPlanDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deployPlanDo) FirstOrInit() (*model.DeployPlan, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeployPlan), nil
	}
}

func (d deployPlanDo) FirstOrCreate() (*model.DeployPlan, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeployPlan), nil
	}
}

func (d deployPlanDo) FindByPage(offset int, limit int) (result []*model.DeployPlan, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deployPlanDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deployPlanDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deployPlanDo) Delete(models ...*model.DeployPlan) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deployPlanDo) withDO(do gen.Dao) *deployPlanDo {
	d.DO = *do.(*gen.DO)
	return d
}
