// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	BusinessUnit      *businessUnit
	CDConfig          *cDConfig
	CIConfig          *cIConfig
	Dependency        *dependency
	DependencyBinding *dependencyBinding
	DeployPlan        *deployPlan
	InstanceConfig    *instanceConfig
	Project           *project
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	BusinessUnit = &Q.BusinessUnit
	CDConfig = &Q.CDConfig
	CIConfig = &Q.CIConfig
	Dependency = &Q.Dependency
	DependencyBinding = &Q.DependencyBinding
	DeployPlan = &Q.DeployPlan
	InstanceConfig = &Q.InstanceConfig
	Project = &Q.Project
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		BusinessUnit:      newBusinessUnit(db, opts...),
		CDConfig:          newCDConfig(db, opts...),
		CIConfig:          newCIConfig(db, opts...),
		Dependency:        newDependency(db, opts...),
		DependencyBinding: newDependencyBinding(db, opts...),
		DeployPlan:        newDeployPlan(db, opts...),
		InstanceConfig:    newInstanceConfig(db, opts...),
		Project:           newProject(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	BusinessUnit      businessUnit
	CDConfig          cDConfig
	CIConfig          cIConfig
	Dependency        dependency
	DependencyBinding dependencyBinding
	DeployPlan        deployPlan
	InstanceConfig    instanceConfig
	Project           project
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		BusinessUnit:      q.BusinessUnit.clone(db),
		CDConfig:          q.CDConfig.clone(db),
		CIConfig:          q.CIConfig.clone(db),
		Dependency:        q.Dependency.clone(db),
		DependencyBinding: q.DependencyBinding.clone(db),
		DeployPlan:        q.DeployPlan.clone(db),
		InstanceConfig:    q.InstanceConfig.clone(db),
		Project:           q.Project.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		BusinessUnit:      q.BusinessUnit.replaceDB(db),
		CDConfig:          q.CDConfig.replaceDB(db),
		CIConfig:          q.CIConfig.replaceDB(db),
		Dependency:        q.Dependency.replaceDB(db),
		DependencyBinding: q.DependencyBinding.replaceDB(db),
		DeployPlan:        q.DeployPlan.replaceDB(db),
		InstanceConfig:    q.InstanceConfig.replaceDB(db),
		Project:           q.Project.replaceDB(db),
	}
}

type queryCtx struct {
	BusinessUnit      *businessUnitDo
	CDConfig          *cDConfigDo
	CIConfig          *cIConfigDo
	Dependency        *dependencyDo
	DependencyBinding *dependencyBindingDo
	DeployPlan        *deployPlanDo
	InstanceConfig    *instanceConfigDo
	Project           *projectDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		BusinessUnit:      q.BusinessUnit.WithContext(ctx),
		CDConfig:          q.CDConfig.WithContext(ctx),
		CIConfig:          q.CIConfig.WithContext(ctx),
		Dependency:        q.Dependency.WithContext(ctx),
		DependencyBinding: q.DependencyBinding.WithContext(ctx),
		DeployPlan:        q.DeployPlan.WithContext(ctx),
		InstanceConfig:    q.InstanceConfig.WithContext(ctx),
		Project:           q.Project.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
