// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newInstanceConfig(db *gorm.DB, opts ...gen.DOOption) instanceConfig {
	_instanceConfig := instanceConfig{}

	_instanceConfig.instanceConfigDo.UseDB(db, opts...)
	_instanceConfig.instanceConfigDo.UseModel(&model.InstanceConfig{})

	tableName := _instanceConfig.instanceConfigDo.TableName()
	_instanceConfig.ALL = field.NewAsterisk(tableName)
	_instanceConfig.ID = field.NewInt64(tableName, "id")
	_instanceConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_instanceConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_instanceConfig.Name = field.NewString(tableName, "name")
	_instanceConfig.BusinessUnitID = field.NewInt64(tableName, "business_unit_id")
	_instanceConfig.Env = field.NewString(tableName, "env")
	_instanceConfig.InstanceType = field.NewString(tableName, "instance_type")
	_instanceConfig.Spec = field.NewField(tableName, "spec")
	_instanceConfig.AttachResources = field.NewField(tableName, "attach_resources")

	_instanceConfig.fillFieldMap()

	return _instanceConfig
}

type instanceConfig struct {
	instanceConfigDo instanceConfigDo

	ALL             field.Asterisk
	ID              field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Name            field.String
	BusinessUnitID  field.Int64
	Env             field.String
	InstanceType    field.String
	Spec            field.Field
	AttachResources field.Field

	fieldMap map[string]field.Expr
}

func (i instanceConfig) Table(newTableName string) *instanceConfig {
	i.instanceConfigDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i instanceConfig) As(alias string) *instanceConfig {
	i.instanceConfigDo.DO = *(i.instanceConfigDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *instanceConfig) updateTableName(table string) *instanceConfig {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.Name = field.NewString(table, "name")
	i.BusinessUnitID = field.NewInt64(table, "business_unit_id")
	i.Env = field.NewString(table, "env")
	i.InstanceType = field.NewString(table, "instance_type")
	i.Spec = field.NewField(table, "spec")
	i.AttachResources = field.NewField(table, "attach_resources")

	i.fillFieldMap()

	return i
}

func (i *instanceConfig) WithContext(ctx context.Context) *instanceConfigDo {
	return i.instanceConfigDo.WithContext(ctx)
}

func (i instanceConfig) TableName() string { return i.instanceConfigDo.TableName() }

func (i instanceConfig) Alias() string { return i.instanceConfigDo.Alias() }

func (i instanceConfig) Columns(cols ...field.Expr) gen.Columns {
	return i.instanceConfigDo.Columns(cols...)
}

func (i *instanceConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *instanceConfig) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["id"] = i.ID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["name"] = i.Name
	i.fieldMap["business_unit_id"] = i.BusinessUnitID
	i.fieldMap["env"] = i.Env
	i.fieldMap["instance_type"] = i.InstanceType
	i.fieldMap["spec"] = i.Spec
	i.fieldMap["attach_resources"] = i.AttachResources
}

func (i instanceConfig) clone(db *gorm.DB) instanceConfig {
	i.instanceConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i instanceConfig) replaceDB(db *gorm.DB) instanceConfig {
	i.instanceConfigDo.ReplaceDB(db)
	return i
}

type instanceConfigDo struct{ gen.DO }

func (i instanceConfigDo) Debug() *instanceConfigDo {
	return i.withDO(i.DO.Debug())
}

func (i instanceConfigDo) WithContext(ctx context.Context) *instanceConfigDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i instanceConfigDo) ReadDB() *instanceConfigDo {
	return i.Clauses(dbresolver.Read)
}

func (i instanceConfigDo) WriteDB() *instanceConfigDo {
	return i.Clauses(dbresolver.Write)
}

func (i instanceConfigDo) Session(config *gorm.Session) *instanceConfigDo {
	return i.withDO(i.DO.Session(config))
}

func (i instanceConfigDo) Clauses(conds ...clause.Expression) *instanceConfigDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i instanceConfigDo) Returning(value interface{}, columns ...string) *instanceConfigDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i instanceConfigDo) Not(conds ...gen.Condition) *instanceConfigDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i instanceConfigDo) Or(conds ...gen.Condition) *instanceConfigDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i instanceConfigDo) Select(conds ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i instanceConfigDo) Where(conds ...gen.Condition) *instanceConfigDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i instanceConfigDo) Order(conds ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i instanceConfigDo) Distinct(cols ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i instanceConfigDo) Omit(cols ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i instanceConfigDo) Join(table schema.Tabler, on ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i instanceConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i instanceConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i instanceConfigDo) Group(cols ...field.Expr) *instanceConfigDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i instanceConfigDo) Having(conds ...gen.Condition) *instanceConfigDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i instanceConfigDo) Limit(limit int) *instanceConfigDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i instanceConfigDo) Offset(offset int) *instanceConfigDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i instanceConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *instanceConfigDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i instanceConfigDo) Unscoped() *instanceConfigDo {
	return i.withDO(i.DO.Unscoped())
}

func (i instanceConfigDo) Create(values ...*model.InstanceConfig) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i instanceConfigDo) CreateInBatches(values []*model.InstanceConfig, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i instanceConfigDo) Save(values ...*model.InstanceConfig) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i instanceConfigDo) First() (*model.InstanceConfig, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceConfig), nil
	}
}

func (i instanceConfigDo) Take() (*model.InstanceConfig, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceConfig), nil
	}
}

func (i instanceConfigDo) Last() (*model.InstanceConfig, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceConfig), nil
	}
}

func (i instanceConfigDo) Find() ([]*model.InstanceConfig, error) {
	result, err := i.DO.Find()
	return result.([]*model.InstanceConfig), err
}

func (i instanceConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InstanceConfig, err error) {
	buf := make([]*model.InstanceConfig, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i instanceConfigDo) FindInBatches(result *[]*model.InstanceConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i instanceConfigDo) Attrs(attrs ...field.AssignExpr) *instanceConfigDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i instanceConfigDo) Assign(attrs ...field.AssignExpr) *instanceConfigDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i instanceConfigDo) Joins(fields ...field.RelationField) *instanceConfigDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i instanceConfigDo) Preload(fields ...field.RelationField) *instanceConfigDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i instanceConfigDo) FirstOrInit() (*model.InstanceConfig, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceConfig), nil
	}
}

func (i instanceConfigDo) FirstOrCreate() (*model.InstanceConfig, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceConfig), nil
	}
}

func (i instanceConfigDo) FindByPage(offset int, limit int) (result []*model.InstanceConfig, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i instanceConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i instanceConfigDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i instanceConfigDo) Delete(models ...*model.InstanceConfig) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *instanceConfigDo) withDO(do gen.Dao) *instanceConfigDo {
	i.DO = *do.(*gen.DO)
	return i
}
