// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newCIConfig(db *gorm.DB, opts ...gen.DOOption) cIConfig {
	_cIConfig := cIConfig{}

	_cIConfig.cIConfigDo.UseDB(db, opts...)
	_cIConfig.cIConfigDo.UseModel(&model.CIConfig{})

	tableName := _cIConfig.cIConfigDo.TableName()
	_cIConfig.ALL = field.NewAsterisk(tableName)
	_cIConfig.ID = field.NewInt64(tableName, "id")
	_cIConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_cIConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cIConfig.Name = field.NewString(tableName, "name")
	_cIConfig.BusinessUnitID = field.NewInt64(tableName, "business_unit_id")
	_cIConfig.ImageRegistry = field.NewString(tableName, "image_registry")
	_cIConfig.ImageRepo = field.NewString(tableName, "image_repo")
	_cIConfig.ImageTagRule = field.NewField(tableName, "image_tag_rule")
	_cIConfig.BuildSpec = field.NewField(tableName, "build_spec")

	_cIConfig.fillFieldMap()

	return _cIConfig
}

type cIConfig struct {
	cIConfigDo cIConfigDo

	ALL            field.Asterisk
	ID             field.Int64
	CreatedAt      field.Time
	UpdatedAt      field.Time
	Name           field.String
	BusinessUnitID field.Int64
	ImageRegistry  field.String
	ImageRepo      field.String
	ImageTagRule   field.Field
	BuildSpec      field.Field

	fieldMap map[string]field.Expr
}

func (c cIConfig) Table(newTableName string) *cIConfig {
	c.cIConfigDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cIConfig) As(alias string) *cIConfig {
	c.cIConfigDo.DO = *(c.cIConfigDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cIConfig) updateTableName(table string) *cIConfig {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.Name = field.NewString(table, "name")
	c.BusinessUnitID = field.NewInt64(table, "business_unit_id")
	c.ImageRegistry = field.NewString(table, "image_registry")
	c.ImageRepo = field.NewString(table, "image_repo")
	c.ImageTagRule = field.NewField(table, "image_tag_rule")
	c.BuildSpec = field.NewField(table, "build_spec")

	c.fillFieldMap()

	return c
}

func (c *cIConfig) WithContext(ctx context.Context) *cIConfigDo { return c.cIConfigDo.WithContext(ctx) }

func (c cIConfig) TableName() string { return c.cIConfigDo.TableName() }

func (c cIConfig) Alias() string { return c.cIConfigDo.Alias() }

func (c cIConfig) Columns(cols ...field.Expr) gen.Columns { return c.cIConfigDo.Columns(cols...) }

func (c *cIConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cIConfig) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["business_unit_id"] = c.BusinessUnitID
	c.fieldMap["image_registry"] = c.ImageRegistry
	c.fieldMap["image_repo"] = c.ImageRepo
	c.fieldMap["image_tag_rule"] = c.ImageTagRule
	c.fieldMap["build_spec"] = c.BuildSpec
}

func (c cIConfig) clone(db *gorm.DB) cIConfig {
	c.cIConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cIConfig) replaceDB(db *gorm.DB) cIConfig {
	c.cIConfigDo.ReplaceDB(db)
	return c
}

type cIConfigDo struct{ gen.DO }

func (c cIConfigDo) Debug() *cIConfigDo {
	return c.withDO(c.DO.Debug())
}

func (c cIConfigDo) WithContext(ctx context.Context) *cIConfigDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cIConfigDo) ReadDB() *cIConfigDo {
	return c.Clauses(dbresolver.Read)
}

func (c cIConfigDo) WriteDB() *cIConfigDo {
	return c.Clauses(dbresolver.Write)
}

func (c cIConfigDo) Session(config *gorm.Session) *cIConfigDo {
	return c.withDO(c.DO.Session(config))
}

func (c cIConfigDo) Clauses(conds ...clause.Expression) *cIConfigDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cIConfigDo) Returning(value interface{}, columns ...string) *cIConfigDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cIConfigDo) Not(conds ...gen.Condition) *cIConfigDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cIConfigDo) Or(conds ...gen.Condition) *cIConfigDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cIConfigDo) Select(conds ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cIConfigDo) Where(conds ...gen.Condition) *cIConfigDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cIConfigDo) Order(conds ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cIConfigDo) Distinct(cols ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cIConfigDo) Omit(cols ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cIConfigDo) Join(table schema.Tabler, on ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cIConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cIConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cIConfigDo) Group(cols ...field.Expr) *cIConfigDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cIConfigDo) Having(conds ...gen.Condition) *cIConfigDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cIConfigDo) Limit(limit int) *cIConfigDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cIConfigDo) Offset(offset int) *cIConfigDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cIConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cIConfigDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cIConfigDo) Unscoped() *cIConfigDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cIConfigDo) Create(values ...*model.CIConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cIConfigDo) CreateInBatches(values []*model.CIConfig, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cIConfigDo) Save(values ...*model.CIConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cIConfigDo) First() (*model.CIConfig, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CIConfig), nil
	}
}

func (c cIConfigDo) Take() (*model.CIConfig, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CIConfig), nil
	}
}

func (c cIConfigDo) Last() (*model.CIConfig, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CIConfig), nil
	}
}

func (c cIConfigDo) Find() ([]*model.CIConfig, error) {
	result, err := c.DO.Find()
	return result.([]*model.CIConfig), err
}

func (c cIConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CIConfig, err error) {
	buf := make([]*model.CIConfig, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cIConfigDo) FindInBatches(result *[]*model.CIConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cIConfigDo) Attrs(attrs ...field.AssignExpr) *cIConfigDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cIConfigDo) Assign(attrs ...field.AssignExpr) *cIConfigDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cIConfigDo) Joins(fields ...field.RelationField) *cIConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cIConfigDo) Preload(fields ...field.RelationField) *cIConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cIConfigDo) FirstOrInit() (*model.CIConfig, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CIConfig), nil
	}
}

func (c cIConfigDo) FirstOrCreate() (*model.CIConfig, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CIConfig), nil
	}
}

func (c cIConfigDo) FindByPage(offset int, limit int) (result []*model.CIConfig, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cIConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cIConfigDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cIConfigDo) Delete(models ...*model.CIConfig) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cIConfigDo) withDO(do gen.Dao) *cIConfigDo {
	c.DO = *do.(*gen.DO)
	return c
}
