// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newDependencyBinding(db *gorm.DB, opts ...gen.DOOption) dependencyBinding {
	_dependencyBinding := dependencyBinding{}

	_dependencyBinding.dependencyBindingDo.UseDB(db, opts...)
	_dependencyBinding.dependencyBindingDo.UseModel(&model.DependencyBinding{})

	tableName := _dependencyBinding.dependencyBindingDo.TableName()
	_dependencyBinding.ALL = field.NewAsterisk(tableName)
	_dependencyBinding.ID = field.NewInt64(tableName, "id")
	_dependencyBinding.CreatedAt = field.NewTime(tableName, "created_at")
	_dependencyBinding.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dependencyBinding.fillFieldMap()

	return _dependencyBinding
}

type dependencyBinding struct {
	dependencyBindingDo dependencyBindingDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (d dependencyBinding) Table(newTableName string) *dependencyBinding {
	d.dependencyBindingDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dependencyBinding) As(alias string) *dependencyBinding {
	d.dependencyBindingDo.DO = *(d.dependencyBindingDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dependencyBinding) updateTableName(table string) *dependencyBinding {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dependencyBinding) WithContext(ctx context.Context) *dependencyBindingDo {
	return d.dependencyBindingDo.WithContext(ctx)
}

func (d dependencyBinding) TableName() string { return d.dependencyBindingDo.TableName() }

func (d dependencyBinding) Alias() string { return d.dependencyBindingDo.Alias() }

func (d dependencyBinding) Columns(cols ...field.Expr) gen.Columns {
	return d.dependencyBindingDo.Columns(cols...)
}

func (d *dependencyBinding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dependencyBinding) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 3)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dependencyBinding) clone(db *gorm.DB) dependencyBinding {
	d.dependencyBindingDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dependencyBinding) replaceDB(db *gorm.DB) dependencyBinding {
	d.dependencyBindingDo.ReplaceDB(db)
	return d
}

type dependencyBindingDo struct{ gen.DO }

func (d dependencyBindingDo) Debug() *dependencyBindingDo {
	return d.withDO(d.DO.Debug())
}

func (d dependencyBindingDo) WithContext(ctx context.Context) *dependencyBindingDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dependencyBindingDo) ReadDB() *dependencyBindingDo {
	return d.Clauses(dbresolver.Read)
}

func (d dependencyBindingDo) WriteDB() *dependencyBindingDo {
	return d.Clauses(dbresolver.Write)
}

func (d dependencyBindingDo) Session(config *gorm.Session) *dependencyBindingDo {
	return d.withDO(d.DO.Session(config))
}

func (d dependencyBindingDo) Clauses(conds ...clause.Expression) *dependencyBindingDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dependencyBindingDo) Returning(value interface{}, columns ...string) *dependencyBindingDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dependencyBindingDo) Not(conds ...gen.Condition) *dependencyBindingDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dependencyBindingDo) Or(conds ...gen.Condition) *dependencyBindingDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dependencyBindingDo) Select(conds ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dependencyBindingDo) Where(conds ...gen.Condition) *dependencyBindingDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dependencyBindingDo) Order(conds ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dependencyBindingDo) Distinct(cols ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dependencyBindingDo) Omit(cols ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dependencyBindingDo) Join(table schema.Tabler, on ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dependencyBindingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dependencyBindingDo) RightJoin(table schema.Tabler, on ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dependencyBindingDo) Group(cols ...field.Expr) *dependencyBindingDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dependencyBindingDo) Having(conds ...gen.Condition) *dependencyBindingDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dependencyBindingDo) Limit(limit int) *dependencyBindingDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dependencyBindingDo) Offset(offset int) *dependencyBindingDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dependencyBindingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *dependencyBindingDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dependencyBindingDo) Unscoped() *dependencyBindingDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dependencyBindingDo) Create(values ...*model.DependencyBinding) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dependencyBindingDo) CreateInBatches(values []*model.DependencyBinding, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dependencyBindingDo) Save(values ...*model.DependencyBinding) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dependencyBindingDo) First() (*model.DependencyBinding, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DependencyBinding), nil
	}
}

func (d dependencyBindingDo) Take() (*model.DependencyBinding, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DependencyBinding), nil
	}
}

func (d dependencyBindingDo) Last() (*model.DependencyBinding, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DependencyBinding), nil
	}
}

func (d dependencyBindingDo) Find() ([]*model.DependencyBinding, error) {
	result, err := d.DO.Find()
	return result.([]*model.DependencyBinding), err
}

func (d dependencyBindingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DependencyBinding, err error) {
	buf := make([]*model.DependencyBinding, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dependencyBindingDo) FindInBatches(result *[]*model.DependencyBinding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dependencyBindingDo) Attrs(attrs ...field.AssignExpr) *dependencyBindingDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dependencyBindingDo) Assign(attrs ...field.AssignExpr) *dependencyBindingDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dependencyBindingDo) Joins(fields ...field.RelationField) *dependencyBindingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dependencyBindingDo) Preload(fields ...field.RelationField) *dependencyBindingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dependencyBindingDo) FirstOrInit() (*model.DependencyBinding, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DependencyBinding), nil
	}
}

func (d dependencyBindingDo) FirstOrCreate() (*model.DependencyBinding, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DependencyBinding), nil
	}
}

func (d dependencyBindingDo) FindByPage(offset int, limit int) (result []*model.DependencyBinding, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dependencyBindingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dependencyBindingDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dependencyBindingDo) Delete(models ...*model.DependencyBinding) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dependencyBindingDo) withDO(do gen.Dao) *dependencyBindingDo {
	d.DO = *do.(*gen.DO)
	return d
}
