// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newDependency(db *gorm.DB, opts ...gen.DOOption) dependency {
	_dependency := dependency{}

	_dependency.dependencyDo.UseDB(db, opts...)
	_dependency.dependencyDo.UseModel(&model.Dependency{})

	tableName := _dependency.dependencyDo.TableName()
	_dependency.ALL = field.NewAsterisk(tableName)
	_dependency.ID = field.NewInt64(tableName, "id")
	_dependency.CreatedAt = field.NewTime(tableName, "created_at")
	_dependency.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dependency.fillFieldMap()

	return _dependency
}

type dependency struct {
	dependencyDo dependencyDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (d dependency) Table(newTableName string) *dependency {
	d.dependencyDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dependency) As(alias string) *dependency {
	d.dependencyDo.DO = *(d.dependencyDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dependency) updateTableName(table string) *dependency {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dependency) WithContext(ctx context.Context) *dependencyDo {
	return d.dependencyDo.WithContext(ctx)
}

func (d dependency) TableName() string { return d.dependencyDo.TableName() }

func (d dependency) Alias() string { return d.dependencyDo.Alias() }

func (d dependency) Columns(cols ...field.Expr) gen.Columns { return d.dependencyDo.Columns(cols...) }

func (d *dependency) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dependency) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 3)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dependency) clone(db *gorm.DB) dependency {
	d.dependencyDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dependency) replaceDB(db *gorm.DB) dependency {
	d.dependencyDo.ReplaceDB(db)
	return d
}

type dependencyDo struct{ gen.DO }

func (d dependencyDo) Debug() *dependencyDo {
	return d.withDO(d.DO.Debug())
}

func (d dependencyDo) WithContext(ctx context.Context) *dependencyDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dependencyDo) ReadDB() *dependencyDo {
	return d.Clauses(dbresolver.Read)
}

func (d dependencyDo) WriteDB() *dependencyDo {
	return d.Clauses(dbresolver.Write)
}

func (d dependencyDo) Session(config *gorm.Session) *dependencyDo {
	return d.withDO(d.DO.Session(config))
}

func (d dependencyDo) Clauses(conds ...clause.Expression) *dependencyDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dependencyDo) Returning(value interface{}, columns ...string) *dependencyDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dependencyDo) Not(conds ...gen.Condition) *dependencyDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dependencyDo) Or(conds ...gen.Condition) *dependencyDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dependencyDo) Select(conds ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dependencyDo) Where(conds ...gen.Condition) *dependencyDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dependencyDo) Order(conds ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dependencyDo) Distinct(cols ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dependencyDo) Omit(cols ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dependencyDo) Join(table schema.Tabler, on ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dependencyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dependencyDo) RightJoin(table schema.Tabler, on ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dependencyDo) Group(cols ...field.Expr) *dependencyDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dependencyDo) Having(conds ...gen.Condition) *dependencyDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dependencyDo) Limit(limit int) *dependencyDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dependencyDo) Offset(offset int) *dependencyDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dependencyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *dependencyDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dependencyDo) Unscoped() *dependencyDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dependencyDo) Create(values ...*model.Dependency) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dependencyDo) CreateInBatches(values []*model.Dependency, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dependencyDo) Save(values ...*model.Dependency) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dependencyDo) First() (*model.Dependency, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependency), nil
	}
}

func (d dependencyDo) Take() (*model.Dependency, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependency), nil
	}
}

func (d dependencyDo) Last() (*model.Dependency, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependency), nil
	}
}

func (d dependencyDo) Find() ([]*model.Dependency, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dependency), err
}

func (d dependencyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dependency, err error) {
	buf := make([]*model.Dependency, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dependencyDo) FindInBatches(result *[]*model.Dependency, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dependencyDo) Attrs(attrs ...field.AssignExpr) *dependencyDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dependencyDo) Assign(attrs ...field.AssignExpr) *dependencyDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dependencyDo) Joins(fields ...field.RelationField) *dependencyDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dependencyDo) Preload(fields ...field.RelationField) *dependencyDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dependencyDo) FirstOrInit() (*model.Dependency, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependency), nil
	}
}

func (d dependencyDo) FirstOrCreate() (*model.Dependency, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dependency), nil
	}
}

func (d dependencyDo) FindByPage(offset int, limit int) (result []*model.Dependency, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dependencyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dependencyDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dependencyDo) Delete(models ...*model.Dependency) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dependencyDo) withDO(do gen.Dao) *dependencyDo {
	d.DO = *do.(*gen.DO)
	return d
}
