// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/richer421/q-metahub/infra/mysql/model"
)

func newInstanceOAM(db *gorm.DB, opts ...gen.DOOption) instanceOAM {
	_instanceOAM := instanceOAM{}

	_instanceOAM.instanceOAMDo.UseDB(db, opts...)
	_instanceOAM.instanceOAMDo.UseModel(&model.InstanceOAM{})

	tableName := _instanceOAM.instanceOAMDo.TableName()
	_instanceOAM.ALL = field.NewAsterisk(tableName)
	_instanceOAM.ID = field.NewInt64(tableName, "id")
	_instanceOAM.CreatedAt = field.NewTime(tableName, "created_at")
	_instanceOAM.UpdatedAt = field.NewTime(tableName, "updated_at")
	_instanceOAM.Name = field.NewString(tableName, "name")
	_instanceOAM.BusinessUnitID = field.NewInt64(tableName, "business_unit_id")
	_instanceOAM.Env = field.NewString(tableName, "env")
	_instanceOAM.SchemaVersion = field.NewString(tableName, "schema_version")
	_instanceOAM.OAMApplication = field.NewField(tableName, "oam_application")
	_instanceOAM.FrontendPayload = field.NewField(tableName, "frontend_payload")

	_instanceOAM.fillFieldMap()

	return _instanceOAM
}

type instanceOAM struct {
	instanceOAMDo instanceOAMDo

	ALL             field.Asterisk
	ID              field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Name            field.String
	BusinessUnitID  field.Int64
	Env             field.String
	SchemaVersion   field.String
	OAMApplication  field.Field
	FrontendPayload field.Field

	fieldMap map[string]field.Expr
}

func (i instanceOAM) Table(newTableName string) *instanceOAM {
	i.instanceOAMDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i instanceOAM) As(alias string) *instanceOAM {
	i.instanceOAMDo.DO = *(i.instanceOAMDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *instanceOAM) updateTableName(table string) *instanceOAM {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.Name = field.NewString(table, "name")
	i.BusinessUnitID = field.NewInt64(table, "business_unit_id")
	i.Env = field.NewString(table, "env")
	i.SchemaVersion = field.NewString(table, "schema_version")
	i.OAMApplication = field.NewField(table, "oam_application")
	i.FrontendPayload = field.NewField(table, "frontend_payload")

	i.fillFieldMap()

	return i
}

func (i *instanceOAM) WithContext(ctx context.Context) *instanceOAMDo {
	return i.instanceOAMDo.WithContext(ctx)
}

func (i instanceOAM) TableName() string { return i.instanceOAMDo.TableName() }

func (i instanceOAM) Alias() string { return i.instanceOAMDo.Alias() }

func (i instanceOAM) Columns(cols ...field.Expr) gen.Columns { return i.instanceOAMDo.Columns(cols...) }

func (i *instanceOAM) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *instanceOAM) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["id"] = i.ID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["name"] = i.Name
	i.fieldMap["business_unit_id"] = i.BusinessUnitID
	i.fieldMap["env"] = i.Env
	i.fieldMap["schema_version"] = i.SchemaVersion
	i.fieldMap["oam_application"] = i.OAMApplication
	i.fieldMap["frontend_payload"] = i.FrontendPayload
}

func (i instanceOAM) clone(db *gorm.DB) instanceOAM {
	i.instanceOAMDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i instanceOAM) replaceDB(db *gorm.DB) instanceOAM {
	i.instanceOAMDo.ReplaceDB(db)
	return i
}

type instanceOAMDo struct{ gen.DO }

func (i instanceOAMDo) Debug() *instanceOAMDo {
	return i.withDO(i.DO.Debug())
}

func (i instanceOAMDo) WithContext(ctx context.Context) *instanceOAMDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i instanceOAMDo) ReadDB() *instanceOAMDo {
	return i.Clauses(dbresolver.Read)
}

func (i instanceOAMDo) WriteDB() *instanceOAMDo {
	return i.Clauses(dbresolver.Write)
}

func (i instanceOAMDo) Session(config *gorm.Session) *instanceOAMDo {
	return i.withDO(i.DO.Session(config))
}

func (i instanceOAMDo) Clauses(conds ...clause.Expression) *instanceOAMDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i instanceOAMDo) Returning(value interface{}, columns ...string) *instanceOAMDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i instanceOAMDo) Not(conds ...gen.Condition) *instanceOAMDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i instanceOAMDo) Or(conds ...gen.Condition) *instanceOAMDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i instanceOAMDo) Select(conds ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i instanceOAMDo) Where(conds ...gen.Condition) *instanceOAMDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i instanceOAMDo) Order(conds ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i instanceOAMDo) Distinct(cols ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i instanceOAMDo) Omit(cols ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i instanceOAMDo) Join(table schema.Tabler, on ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i instanceOAMDo) LeftJoin(table schema.Tabler, on ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i instanceOAMDo) RightJoin(table schema.Tabler, on ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i instanceOAMDo) Group(cols ...field.Expr) *instanceOAMDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i instanceOAMDo) Having(conds ...gen.Condition) *instanceOAMDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i instanceOAMDo) Limit(limit int) *instanceOAMDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i instanceOAMDo) Offset(offset int) *instanceOAMDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i instanceOAMDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *instanceOAMDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i instanceOAMDo) Unscoped() *instanceOAMDo {
	return i.withDO(i.DO.Unscoped())
}

func (i instanceOAMDo) Create(values ...*model.InstanceOAM) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i instanceOAMDo) CreateInBatches(values []*model.InstanceOAM, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i instanceOAMDo) Save(values ...*model.InstanceOAM) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i instanceOAMDo) First() (*model.InstanceOAM, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceOAM), nil
	}
}

func (i instanceOAMDo) Take() (*model.InstanceOAM, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceOAM), nil
	}
}

func (i instanceOAMDo) Last() (*model.InstanceOAM, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceOAM), nil
	}
}

func (i instanceOAMDo) Find() ([]*model.InstanceOAM, error) {
	result, err := i.DO.Find()
	return result.([]*model.InstanceOAM), err
}

func (i instanceOAMDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InstanceOAM, err error) {
	buf := make([]*model.InstanceOAM, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i instanceOAMDo) FindInBatches(result *[]*model.InstanceOAM, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i instanceOAMDo) Attrs(attrs ...field.AssignExpr) *instanceOAMDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i instanceOAMDo) Assign(attrs ...field.AssignExpr) *instanceOAMDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i instanceOAMDo) Joins(fields ...field.RelationField) *instanceOAMDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i instanceOAMDo) Preload(fields ...field.RelationField) *instanceOAMDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i instanceOAMDo) FirstOrInit() (*model.InstanceOAM, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceOAM), nil
	}
}

func (i instanceOAMDo) FirstOrCreate() (*model.InstanceOAM, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceOAM), nil
	}
}

func (i instanceOAMDo) FindByPage(offset int, limit int) (result []*model.InstanceOAM, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i instanceOAMDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i instanceOAMDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i instanceOAMDo) Delete(models ...*model.InstanceOAM) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *instanceOAMDo) withDO(do gen.Dao) *instanceOAMDo {
	i.DO = *do.(*gen.DO)
	return i
}
